ALTER TABLE "Product"
ADD COLUMN IF NOT EXISTS "promoPriceHt" DECIMAL(14, 2),
ADD COLUMN IF NOT EXISTS "promoPriceTtc" DECIMAL(14, 2),
ADD COLUMN IF NOT EXISTS "promoPriceActive" BOOLEAN NOT NULL DEFAULT false;
